### ISSUE TITLE
maxVolume for 'every time interval' in the window is not generated.

### ISSUE THREAD

**Issue by shazzing** [adnanaziz/epicode#1]
the maxVolume is only generated in the current version of code, at time-interval that had trafficeVolume in the input. The in between interval maxVolume are not generated.
For example  for the input 
vector<trafficElement> trafficVol = {{0, 1.3}, {2, 2.5}, {3, 3.7}, {5, 1.4}, {6, 2.6}, {8, 2.2}, {9, 1.7}, {14, 1.7}};

the output is : { 0 ,1.3 }, { 2 ,2.5 }, { 3 ,3.7 }, { 5 ,3.7 }, { 6 ,3.7 }, { 8 ,2.6 }, { 9 ,2.6 }, { 14 ,1.7 }, 

it should be :  { 0 ,1.3 }, { 1 ,1.3 }, { 2 ,2.5 }, { 3 ,3.7 }, { 4 ,3.7 }, { 5 ,3.7 }, { 6 ,3.7 }, { 7 ,2.6 }, { 8 ,2.6 }, { 9 ,2.6 }, { 10 ,2.2 }, { 11 ,2.2 }, { 12 ,1.7 }, { 13 ,0 }, { 14 ,1.7 }, 
Also per diagram 22.5(b)

Unless I misunderstood the problem ?

**Comment by thlee-uber** [comment]
Hey @shazzing ,

Thanks for the issue report, and there is some confusion here that we want the maximum traffic volume for each input timestamp instead of each timestamp.  Figure is used to explain how the maximum traffic volume of each timestamp would look like but it actually costs your confusion here.

Thanks for your feedback, and let us know if you have any other problem.
